const GROUP_LABELS: Record<string, string> = {
  META: "笔录与人员信息",
  PROC: "程序告知与确认",
  CASE: "报案与诈骗经过",
  PREV: "反诈宣传",
  RISK: "风险提示与处置",
  CASH: "取款与预约",
  TIME: "时间地点",
  PRIV: "个人信息泄露",
  LEAD: "首次引流",
  MOTIVE: "持续联系原因",
  CONTACT: "联系人与渠道切换",
  MONEY: "线上资金",
  OFFLINE: "线下交付",
  EXTRA: "补充事实",
  EVID: "证据留存",
};

const SCOPE_LABELS: Record<string, string> = {
  structural: "结构规则",
  common: "通用规则",
  conditional: "条件规则",
  repeated: "逐项核对",
  base: "基础规则",
};

const FACT_LABELS: Record<string, string> = {
  "record.started_at": "询问开始时间",
  "record.location": "询问地点",
  "record.interviewers": "询问人员",
  "record.respondent": "被询问人",
  "record.signatures": "签名确认",
  "procedure.truth_notice_confirmed": "如实作答告知确认",
  "procedure.rights_notice_read": "权利义务告知",
  "procedure.rights_request": "权利请求",
  "procedure.recusal_requested": "回避申请",
  "procedure.key_information_reconfirmed": "重要信息再次确认",
  "procedure.statement_confirmed_true": "陈述真实性确认",
  "procedure.record_reviewed": "笔录已阅看",
  "procedure.record_matches_statement": "笔录与陈述一致",
  "victim.name": "姓名",
  "victim.gender": "性别",
  "victim.age": "年龄",
  "victim.occupation": "职业",
  "victim.id_number": "身份证件号码",
  "victim.phone": "联系电话",
  "victim.education": "文化程度",
  "victim.employer": "工作单位",
  "case.report_reason": "报案原因",
  "case.fraud_method": "诈骗方式",
  "case.location": "案发地点",
  "case.initial_channel": "首次联系渠道",
  "case.contact_method": "联系方式",
  "case.total_loss": "损失总额",
  "case.timeline": "诈骗经过时间线",
  "case.initial_contact": "首次接触情况",
  "case.channel_changes": "联系渠道变化",
  "case.fraud_tools": "诈骗工具",
  "case.payment_reason": "付款原因",
  "case.payment_summary": "付款概况",
  "case.rebate_summary": "返利概况",
  "case.additional_statement": "其他补充事实",
  "prevention.received_publicity": "是否接受反诈宣传",
  "prevention.community_police_publicity": "社区民警反诈宣传",
  "prevention.anti_fraud_app_installed": "国家反诈中心 App 安装情况",
  "risk.payment_warning_received": "支付风险提示",
  "risk.payment_warning_channel": "风险提示渠道",
  "risk.payment_warning_content": "风险提示内容",
  "risk.account_loss_reported": "被骗后账户处置",
  "risk.loss_report_time": "账户处置时间",
  "risk.post_report_transfers": "报案后是否继续转账",
  "risk.phone_card_real_name": "电话卡实名情况",
  "risk.phone_warning_received": "电话卡风险提示",
  "risk.victim_chat_real_name": "被害人聊天账号实名",
  "risk.suspect_chat_real_name": "嫌疑人聊天账号实名",
  "evidence.voice_recording_exists": "语音通话是否录音",
  "evidence.voice_recording_available": "语音录音是否可提供",
  "evidence.records_retained": "相关记录是否留存",
  "evidence.record_types": "留存记录类型",
  "evidence.can_provide": "记录能否提供",
  "offline.suspect_appointment": "嫌疑人预约拿款信息",
  "offline.appointment_time": "预约时间",
  "offline.appointment_location": "预约地点",
  "offline.appointment_amount": "预约金额",
  "cash.bank_appointment": "银行取款预约",
  "cash.bank_warning_received": "银行风险提示",
  "cash.bank_warning_channel": "银行提示渠道",
  "cash.withdrawal_count": "取款笔数",
  "timeline.incident_at": "案发时间",
  "timeline.incident_district": "案发区县",
  "timeline.incident_street": "案发街道",
  "timeline.incident_community": "案发社区",
  "timeline.first_contact_at": "最早联系时间",
  "privacy.disclosure_occurred": "案发前是否泄露个人信息",
  "privacy.disclosure_time": "个人信息泄露时间",
  "privacy.disclosure_reason": "个人信息泄露原因",
  "privacy.disclosed_information": "泄露的个人信息",
  "contact.initial_channel": "首次联系渠道",
  "contact.initial_account": "首次联系账号",
  "contact.initial_content": "首次联系内容",
  "contact.switch_count": "后续渠道切换次数",
  "motive.continued_contact_reason": "持续联系原因",
  "money.gross_loss": "被骗总额",
  "money.rebate_total": "返利总额",
  "money.net_loss": "净损失",
  "money.transfer_control_method": "资金转出控制方式",
  "money.remote_control_used": "是否被远程控制",
  "money.credentials_disclosed": "是否泄露支付凭证",
  "online_money.transfer_count": "线上转账笔数",
  "online_money.total": "线上转账总额",
};

export const displayGroupLabel = (group: string) => GROUP_LABELS[group] ?? group;
export const displayRuleScope = (scope: string) => SCOPE_LABELS[scope] ?? scope;
export const displayFactLabel = (fact: string) => FACT_LABELS[fact] ?? fact;
